# Generated by Django 3.2.16 on 2022-10-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='teamimage')),
                ('desc', models.TextField()),
            ],
        ),
    ]
